# https://github.com/microsoft/vscode-dev-containers/tree/v0.245.0/containers/dotnet-fsharp/.devcontainer/base.Dockerfile

ARG VARIANT="6.0-focal"
FROM mcr.microsoft.com/vscode/devcontainers/dotnet:0-${VARIANT}

curl -sSL gobinaries.com/zakuro9715/z | sh
